### ISSUE TITLE
セットアップした日以外の、Slack 通知が動いてなさそう

### ISSUE THREAD

**Issue by BaseW** [BaseW/mynews#36]
セットアップした日以外の、Slack 通知が動いてなさそう
-> GAS は実行されているよう
-> 原因を調べる

_Originally posted by @BaseW in https://github.com/BaseW/mynews/issues/28#issuecomment-1137089173_

**Comment by BaseW** [comment]
トリガーを設定していたバージョンをアーカイブしていたので、Head を対象にトリガーを設定し直した。

**Comment by wada-avita** [comment]
設定をし直したところ、動作した。

**Comment by BaseW** [comment]
設定をし直したところ、動作した。
